# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-13 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('wave3', models.FloatField(null=True)),
                ('wave_evaluate3', models.FloatField(null=True)),
                ('risk3', models.FloatField(null=True)),
                ('risk_evaluate3', models.FloatField(null=True)),
                ('sharp3', models.FloatField(null=True)),
                ('sharp_evaluate3', models.FloatField(null=True)),
                ('return_rate', models.FloatField(null=True)),
                ('rank', models.IntegerField(null=True)),
                ('update_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
