# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=512)),
                ('content', models.TextField()),
                ('update_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
