# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo2', '0002_pagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinfo',
            name='fid',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundinfo',
            name='risk_evaluate3',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='fundinfo',
            name='sharp_evaluate3',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='fundinfo',
            name='wave_evaluate3',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
